export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  HR: 'HR',
  FINANCIAL_MANAGER: 'FINANCIAL_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  BOOKING_MANAGER: 'BOOKING_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
} as const

export const OUTLETS = {
  WK_JTN: { code: 'WK-JTN', name: 'Wasabi Kitchen Jatinangor' },
  WK_KCR: { code: 'WK-KCR', name: 'Wasabi Kitchen Kiaracondong' },
  BM_JTN: { code: 'BM-JTN', name: 'Bukari Mart Jatinangor' },
} as const

export const WORK_SHIFTS = {
  MORNING: 'MORNING',
  EVENING: 'EVENING',
  NIGHT: 'NIGHT',
  FULL_DAY: 'FULL_DAY',
} as const

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  SICK_LEAVE: 'SICK_LEAVE',
  ANNUAL_LEAVE: 'ANNUAL_LEAVE',
} as const

export const REVENUE_TYPES = {
  DINE_IN: 'DINE_IN',
  TAKEAWAY: 'TAKEAWAY',
  ONLINE_ORDER: 'ONLINE_ORDER',
  FACILITY_RENTAL: 'FACILITY_RENTAL',
} as const

export const BOOKING_TYPES = {
  INDOOR_DINING: 'INDOOR_DINING',
  OUTDOOR_DINING: 'OUTDOOR_DINING',
  INDOOR_LESEHAN: 'INDOOR_LESEHAN',
  OUTDOOR_LESEHAN: 'OUTDOOR_LESEHAN',
  SINGING_ROOM: 'SINGING_ROOM',
  PUSPAWARNA_AUDITORIUM: 'PUSPAWARNA_AUDITORIUM',
  PUSPAWARNA_CLASS_ROOM: 'PUSPAWARNA_CLASS_ROOM',
} as const

export const PROJECT_TYPES = {
  MARKETING_PROGRAM: 'MARKETING_PROGRAM',
  CRM_PROGRAM: 'CRM_PROGRAM',
  NEW_MENU_DEVELOPMENT: 'NEW_MENU_DEVELOPMENT',
} as const

export const TASK_PRIORITIES = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const

export const TASK_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const

export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: 'view_dashboard',

  // HR & Personnel
  VIEW_EMPLOYEES: 'view_employees',
  CREATE_EMPLOYEES: 'create_employees',
  UPDATE_EMPLOYEES: 'update_employees',
  DELETE_EMPLOYEES: 'delete_employees',
  MANAGE_ATTENDANCE: 'manage_attendance',
  VIEW_ATTENDANCE_REPORTS: 'view_attendance_reports',

  // Finance
  VIEW_FINANCIAL_REPORTS: 'view_financial_reports',
  CREATE_FINANCIAL_REPORTS: 'create_financial_reports',
  APPROVE_FINANCIAL_REPORTS: 'approve_financial_reports',
  EXPORT_FINANCIAL_DATA: 'export_financial_data',

  // Inventory
  VIEW_INVENTORY: 'view_inventory',
  MANAGE_INVENTORY: 'manage_inventory',
  VIEW_INVENTORY_REPORTS: 'view_inventory_reports',

  // Bookings
  VIEW_BOOKINGS: 'view_bookings',
  MANAGE_BOOKINGS: 'manage_bookings',
  APPROVE_BOOKINGS: 'approve_bookings',

  // Projects
  VIEW_PROJECTS: 'view_projects',
  MANAGE_PROJECTS: 'manage_projects',

  // System
  MANAGE_USERS: 'manage_users',
  MANAGE_OUTLETS: 'manage_outlets',
  VIEW_SYSTEM_LOGS: 'view_system_logs',
} as const

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [USER_ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.CREATE_EMPLOYEES,
    PERMISSIONS.UPDATE_EMPLOYEES,
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE_REPORTS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.APPROVE_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY_REPORTS,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.MANAGE_BOOKINGS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.MANAGE_PROJECTS,
  ],

  [USER_ROLES.HR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.CREATE_EMPLOYEES,
    PERMISSIONS.UPDATE_EMPLOYEES,
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE_REPORTS,
  ],

  [USER_ROLES.FINANCIAL_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.CREATE_FINANCIAL_REPORTS,
    PERMISSIONS.APPROVE_FINANCIAL_REPORTS,
    PERMISSIONS.EXPORT_FINANCIAL_DATA,
  ],

  [USER_ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY_REPORTS,
  ],

  [USER_ROLES.BOOKING_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.MANAGE_BOOKINGS,
    PERMISSIONS.APPROVE_BOOKINGS,
  ],

  [USER_ROLES.EMPLOYEE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_ATTENDANCE,
  ],
} as const